image: atlassian/default-image:3

definitions: 
  steps:
    - step: &build-test
        name: Build and test
        image: golang:1.19
        script:
          - go build -v ./...
          - go test -v -covermode=count -coverprofile=coverage.out ./...
    - step: &deploy
        name: Deploy
        deployment: Production
        trigger: manual
        script:
          - curl -L https://fly.io/install.sh | sh
          - /root/.fly/bin/flyctl -t $FLY_API_TOKEN deploy --remote-only

pipelines:
  default:
    - step: *build-test
    - step: *deploy  
