/* autogenerated by Processing revision 1282 on 2022-07-28 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class App extends PApplet {

    /**
     * Follow 1
     * based on code from Keith Peters.
     *
     * A line segment is pushed and pulled by the cursor.
     */

    float x = 100;
    float y = 100;
    float angle1 = 0.0f;
    float segLength = 50;

    public void setup() {
        /* size commented out by preprocessor */;
        strokeWeight(20.0f);
        stroke(255, 100);
    }

    public void draw() {
        background(0);

        float dx = mouseX - x;
        float dy = mouseY - y;
        angle1 = atan2(dy, dx);
        x = mouseX - (cos(angle1) * segLength);
        y = mouseY - (sin(angle1) * segLength);

        segment(x, y, angle1);
        ellipse(x, y, 20, 20);
    }

    public void segment(float x, float y, float a) {
        pushMatrix();
        translate(x, y);
        rotate(a);
        line(0, 0, segLength, 0);
        popMatrix();
    }

    public void mouseClicked() {
        if (segLength == 50) {
            segLength = 100;
        } else {
            segLength = 50;
        }
    }


    public void settings() { size(640, 360); }

    static public void main(String[] passedArgs) {
        String[] appletArgs = new String[] { "App" };
        if (passedArgs != null) {
            PApplet.main(concat(appletArgs, passedArgs));
        } else {
            PApplet.main(appletArgs);
        }
    }
}
