name: Test and Deploy API to dev

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]
    
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:

  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -covermode=count -coverprofile=coverage.out ./...
      
    - name: gcov2lcov-action
      uses: jandelgado/gcov2lcov-action@v1.0.9
      
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./lconv.info
      
  deploy:
      name: Deploy app
      needs: build-test
      environment: 
        name: dev
        url: https://comp4050-square-api.fly.dev
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only
        
