name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        cache: true

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -covermode=count -coverprofile=coverage.out ./...
      
    - name: Generate lcov file
      uses: jandelgado/gcov2lcov-action@v1.0.9
      
    - name: Coveralls - Test coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage.lcov
      
